# Project information
site_name: CONFIRE SHERLOCK
site_description: 'CONFIRE SHERLOCK Documentation'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.sherlock3.stueber.co.uk'

# Copyright
copyright: © 2021 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'View on GitHub'
repo_url: 'https://github.com/stuebersystems/doc.sherlock.en'

# Theming
theme: 
    name: material
    custom_dir: overrides
    language: en
    features:
        - instant
    palette:
        primary: 'indigo'
        accent: 'amber'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Legal links
extra:
  legal:
    - label: Imprint
      link: https://www.stueber.co.uk/imprint.php
    - label: Privacy
      link: https://legal.stueber.co.uk/privacy.php

# Customization
extra_css:
    - assets/css/custom.css
    
# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
    - Overview: index.md
    - Introduction: introduction.md
    - Whats new?: changelog.md
    - Requirements: requirements.md
    - How To Get Started: howto.md
    - Tips & Tricks: tips.md
    - The API: api.md
    - The CONSOLE: console.md
